object SignConstants {
    const val variantNameDebug = "debug"
    const val variantNameRelease = "release"
    const val variantNameEnhanced = "enhanced"
    const val versionNameSuffixDebug = "-DEBUG"
    const val versionNameSuffixRelease = "-RELEASE"
    const val versionNameSuffixEnhanced = "-PRIME"
    const val appIdSuffixDebug = ".debug"
    // const val appIdSuffixRelease = ".release"
    const val appIdSuffixEnhanced = ".prime"
    const val varAppName = "app_name"
    const val varWaifuViewer = "waifu_viewer"
    const val valueAppNameDebug = "Waifu Debug"
    const val homeWaifuViewerDebug = "Waifu Debug"
    const val valueAppNameEnhanced = "Waifu Prime"
    const val homeWaifuViewerEnhanced = "Waifu Prime"
    const val keyAliasSign = "keyAliasSign"
    const val keyPassword = "keyPassword"
    const val keyStoreFile = "keyStoreFile"
    const val storePassword = "storePassword"
}